var languageElements = { "en":{
    "user-label":"User:",
    "language-label":"Language:",
    "show-call-center":"CallCenter",
    "show-summary": "Summary",
    "share-summary": "Share Summary",
    "show-wellness":"Wellness",
    "show-intake":"Intake",
    "show-sensors":"Sensors",
    "show-blood-pressure":"BP",
    "show-pox":"PulseOx",
    "show-thermometer":"Thermometer",
    "show-weight":"Weight",
    "show-stethoscope":"Stethoscope",
    "show-glucometer":"Glucometer",
    "show-camera":"Camera",
    "show-otoscope":"Otoscope",
    "showDigitalCamera":"DigitalCamera",
    "show-external-app":"ExternalApp",
    "show-clinic":"Clinic",
    "clinic":"Clinic Name:",
    "select-clinic":"selectClinic",
    "show-login":"Login",
    "show-signup":"Signup",
    "show-new-session":"New Session",
    "showSaveSession":"Save Session",
    "showRestoreSession":"Restore Session",
    "save-session":"Save Test Session",
    "restoreSession":"restore test Session",
    "submit-url":"Post Url",
    "intake":"Intake Value",
    "sensor":"Sensor Value",
    "proxy":"Proxy Value",
    "bnt-reject":"Cancel",
    "bnt-accept":"Accept",
    "menu-tab":"Menus",
    "clinic-tab":"Clinics",
    "measurement-tab":"Measurements",
    "intake-tab":"Set Intake",
    "health-history-tab": "Health History",
    "user-actions":"User Actions",
    "end-session":"End Session",
    "save-health-data":"Save Data",
    "clinics-header":"Clinics",
    "clinic-name-label":"Clinic Name",
    "take-blood-pressure-measurement":"Take Measurement",
    "take-pulse-ox-measurement":"Take Measurement",
    "take-thermometer-measurement":"Take Measurement",
    "temperature-label":"Temperature",
    "temperature-unit-label":"Unit",
    "take-glucometer-measurement":"Take Measurement",
    "blood-sugar-label":"Blood Sugar",
    "blood-sugar-unit-label":"Unit",
    "take-weight-scale-measurement":"Take Measurement",
    "weight-unit-label":"Unit",
    "take-spirometer-measurement":"Take Measurement",
    "get-sensors":"Show Sensors",
    "name-label":"Name:",
    "value-label":"Value:",
    "units-label":"Units:",
    "device-label":"Device:",
    "set-measurement":"Set Measurement",
    "set-note":"Set Note",
    "first-name-label":"First Name:",
    "last-name-label":"Last Name:",
    "date-of-birth-label":"Date of Birth:",
    "gender-label":"Gender:",
    "height-label":"Height:",
    "weight-label":"Weight:",
    "allergiesLabel":"Allergies",
    "medications-label":"Current Medications",
    "conditions-label":"Current Conditions",
    "medical-history-label":"Medical History",
    "has-insurance-label":"I have insurance",
    "insurance-name-label":"Insurance Provider",
    "insurance-id-label":"Insurance Policy Number",
    "no-insurance-label":"I don't have insurance",
    "insurance-plan-not-listed-label":"Plan not listed/Prefer not to say",
    "visit-details-label":"What is this visit about?"
},
"es":{
    "user-label": "Usuario",
    "language-label": "Idioma",
    "show-call-center": "CallCenter",
    "show-summary": "Summary",
    "share-summary": "Share Summary",
    "show-wellness": "Bienestar",
    "show-intake": "Ingesta",
    "show-sensors": "Sensores",
    "show-blood-pressure": "BP",
    "show-pox": "PulseOx",
    "show-thermometer": "Termómetro",
    "show-weight": "Peso",
    "show-stethoscope": "Estetoscopio",
    "show-glucometer": "Glucometer",
    "show-camera": "Cámara",
    "show-otoscope": "Otoscopio",
    "showDigitalCamera": "DigitalCamera",
    "show-external-app": "ExternalApp",
    "show-clinic": "Clínica",
    "clinic": "Nombre de la clínica:",
    "select-clinic": "selectClinic",
    "show-login": "Iniciar sesión",
    "show-signup": "Registrarse",
    "show-new-session": "Nueva sesión",
    "showSaveSession": "Guardar sesión",
    "showRestoreSession": "Restaurar sesión",
    "save-session": "guardar sesión de prueba",
    "restoreSession": "restaurar sesión de prueba",
    "submit-url": "Publicar URL",
    "intake": "Valor de admisión",
    "sensor": "Valor del sensor",
    "proxy": "Valor de proxy",
    "bnt-reject": "Cancelar",
    "bnt-accept": "Aceptar",
    "menu-tab": "Menús",
    "clinic-tab": "Clínicas",
    "MeasurementTab": "Medidas",
    "health-history-tab": "Historia de salud",
    "ingestab": "Establecer ingesta",
    "user-actions": "Acciones del usuario",
    "end-session": "Finalizar sesión",
    "save-health-data": "Guardar datos",
    "clinics-header": "Clínicas",
    "clinic-name-label": "Nombre de la clínica",
    "take-blood-pressure-measurement": "Tomar medidas",
    "take-pulse-ox-measurement": "Tomar medidas",
    "take-thermometer-measurement": "Tomar medidas",
    "temperature-label": "Temperatura",
    "temperature-unit-label": "Unidad",
    "take-glucometer-measurement": "Tomar medidas",
    "blood-sugar-label": "Azúcar en sangre",
    "blood-sugar-unit-label": "Unidad",
    "take-weight-scale-measurement": "Tomar medidas",
    "weight-unit-label": "Unidad",
    "take-spirometer-measurement": "Tomar medidas",
    "get-sensors": "Mostrar sensores",
    "name-label": "Nombre:",
    "value-label": "Valor:",
    "unitLabel": "Unidades:",
    "device-label": "Dispositivo:",
    "set-measurement": "Establecer medida",
    "set-note": "Establecer nota",
    "first-name-label": "Nombre:",
    "last-name-label": "Apellido:",
    "date-of-birth-label": "Fecha de nacimiento:",
    "gender-label": "Sexo:",
    "height-label": "Alto:",
    "weight-label": "Peso:",
    "allergiesLabel": "Alergias",
    "medications-label": "Medicamentos actuales",
    "conditions-label": "Condiciones actuales",
    "medical-history-label": "Historial médico",
    "has-insurance-label": "Tengo seguro",
    "insurance-name-label": "Proveedor de seguros",
    "insurance-id-label": "Número de póliza de seguro",
    "no-insurance-label": "No tengo seguro",
    "insurance-plan-not-listed-label": "Plan no listado / Prefiero no decirlo",
    "visit-details-label": "¿De qué se trata esta visita?"
}
};

function setLanguage(language){
    language=language.substring(0, 2);
    var languageElementArray = languageElements[language];
    for (var key in languageElementArray) {
        element = document.getElementById(key);
        if (element != null && element !== 'undefined'){
        element.innerHTML=languageElementArray[key];
        }
    }
    
}